default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: uwshrtnr_dev

test:
  <<: *default
  database: uwshrtnr_test

production:
  <<: *default
  database: uwshrtnr_prod
