default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: shrtnr_development

test:
  <<: *default
  database: shrtnr_test

production:
  <<: *default
  database: shrtnr_production
