development:
  client_id: 'p3BAJ0y0W2TywjCStJUpk9etw'
  client_secret: 'CfLOX9jn3HWSw1r51WF2Y0OAarAprtVeRiU4pgosq7vAd9y1nj'

test:
  client_id: 'p3BAJ0y0W2TywjCStJUpk9etw'
  client_secret: 'CfLOX9jn3HWSw1r51WF2Y0OAarAprtVeRiU4pgosq7vAd9y1nj'
