development:
  client_id: 'VqKQCUSXPgzztTzXvpQjBELZo'
  client_secret: 'gqizFQ5zabc6SBcvXJNuIXMHydrBc2tFb7H1mYios2BwlQFVvE'

test:
  client_id: 'VqKQCUSXPgzztTzXvpQjBELZo'
  client_secret: 'gqizFQ5zabc6SBcvXJNuIXMHydrBc2tFb7H1mYios2BwlQFVvE'
