development:
  TWITTER_CLIENT_ID: 'PAQomNOuXDaaE0JKTFOlh4zgZ'
  TWITTER_CLIENT_SECRET: 'F8X9VMLbYd9RoAepsCcBUnHjEDsez5QLZVT3A8jKHZ04H83r3x'

test:
  TWITTER_CLIENT_ID: 'PAQomNOuXDaaE0JKTFOlh4zgZ'
  TWITTER_CLIENT_SECRET: 'F8X9VMLbYd9RoAepsCcBUnHjEDsez5QLZVT3A8jKHZ04H83r3x'
